{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Release.Name }}-ingress"
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.ingress.clusterIssuer }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tlsSecretName }}
  tls:
    - hosts:
        - "{{ .Values.ingress.domain }}"
      secretName: "{{ .Values.ingress.tlsSecretName }}"
  {{- end }}
  rules:
    - host: "{{ .Values.ingress.domain }}"
      http:
        paths:
          - pathType: Prefix
            path: "{{ .Values.ingress.path }}"
            backend:
              service:
                name: "{{ .Release.Name }}-service"
                port:
                  number: 80
{{- end }}