image:
  repository: ghcr.io/prod-legit/namixcode_frontend
  tag: "latest"
  pullPolicy: IfNotPresent

imagePullSecrets: []

ingress:
  enabled: false
  className: traefik
  clusterIssuer: letsencrypt-prod
  path: /
  domain: example.com
  tlsSecretName: ""

config:
  api_url: https://example.com/api