name: Deploy

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Image tag for deploy"
        default: latest
        type: string
        required: false

  workflow_call:
    inputs:
      image_tag:
        description: "Image tag for deploy"
        type: string
        required: true

env:
  RELEASE_NAME: starlink-frontend
  REGISTRY: ghcr.io

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout-cone-mode: false
          sparse-checkout: |
            helm
      - name: Create kube config
        run: |
          mkdir -p $HOME/.kube/
          echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config
          chmod 600 $HOME/.kube/config
      - name: Install helm
        run: |
          curl -LO https://get.helm.sh/helm-v3.8.0-linux-amd64.tar.gz
          tar -zxvf helm-v3.8.0-linux-amd64.tar.gz
          mv linux-amd64/helm /usr/local/bin/helm
          helm version
      - name: Deploy
        run: |
          helm upgrade --install --atomic --timeout 3m ${{ env.RELEASE_NAME }} ./helm \
            --set image.tag=${{ inputs.image_tag }} \
            --set image.pullSecret=${{ secrets.PULL_SECRET }} \
            --set ingress.domain=${{ vars.DOMAIN }} \
            --set ingress.tlsSecretName=${{ secrets.TLS_SECRET_NAME }}